import py1
def test_paros_test():
    assert py1.paros(2) == True
    assert py1.paros(3) == False
    assert py1.paros(4) == True
    assert py1.paros(5) == False
    assert py1.paros(6) == True
    assert py1.paros(7) == False
    assert py1.paros(8) == True
    assert py1.paros(9) == False
    assert py1.paros(10) == True
    assert py1.paros(11) == False
    assert py1.paros(12) == True
    assert py1.paros(13) == False
    assert py1.paros(14) == True
    assert py1.paros(15) == False
    assert py1.paros(16) == True
    assert py1.paros(17) == False
    assert py1.paros(18) == True
    assert py1.paros(19) == False
    assert py1.paros(20) == True
    assert py1.paros(21) == False
    assert py1.paros(22) == True
    assert py1.paros(23) == False
    assert py1.paros(24) == True
    assert py1.paros(25) == False
    assert py1.paros(26) == True
    assert py1.paros(27) == False
    assert py1.paros(28) == True
    assert py1.paros(29) == False
    assert py1.paros(30) == True
    assert py1.paros(31) == False
    assert py1.paros(32) == True
    assert py1.paros(33) == False
    assert py1.paros(34) == True
    assert py1.paros(35) == False
    assert py1.paros(36) == True
    assert py1.paros(37) == False
    assert py1.paros(38) == True
    assert py1.paros(39) == False
    assert py1.paros(40) == True
    assert py1.paros(41) == False
    assert py1.paros(42) == True
  